Repository dejan-xd/Chess_DSL, pull requests merged in 2021-12, with the labels that each got.

#15 Creating rules for the Spain language. Close #8
  textX/chess_rules.tx
Labels: user story

#17 Feature/text x
  textX/chess_rules.tx
Labels: user story

#18 Create main menu GUI. Close #7
  GUI.py
  Json.py
  Launch.py
  images/Icon.png
  requirements.txt
  settings.json
Labels: user story

#19 Create audio stream for chess game Close #10
  GUI.py
  Json.py
  audio/capture.wav
  audio/castle.wav
  audio/check.wav
  audio/move.wav
  settings.json
Labels: user story

#20 Draw game state. Close #13
  .vscode/launch.json
  ChessMain.py
  GUI.py
  Json.py
  images/bB.png
  images/bK.png
  images/bN.png
  images/bQ.png
  images/bR.png
  images/bp.png
  images/wB.png
  images/wK.png
  images/wN.png
  images/wQ.png
  images/wR.png
  images/wp.png
  settings.json
Labels: user story

#22 IO text in game's console Close #11
  ChessMain.py
  InputThread.py
  settings.json
Labels: user story

#24 Create game state move logic. Close #23
  .gitignore
  .vscode/launch.json
  ChessMain.py
  GUI.py
  GameState.py
  InputThread.py
  Json.py
  Move.py
  Setup.py
  settings.json
Labels: user story

#33 Undo move Close #26
  ChessMain.py
  GameState.py
  InputThread.py
  settings.json
Labels: user story

#34 Feature/json
  JsonParser.py
Labels: user story

#35 Animate logic. Close #32
  ChessMain.py
  Launch.py
  settings.json
Labels: user story

#36 Chess notation. Close #28
  ChessMain.py
  Move.py
Labels: user story

#37 Piece move logic. Close #25
  ChessMain.py
  GameState.py
  JsonParser.py
  Launch.py
  Move.py
Labels: user story

#42 Create castling logic. Close #38
  CastleRights.py
  ChessMain.py
  GameState.py
  InputThread.py
  Move.py
Labels: bug, user story

#43 Fix game audio Close #41
  ChessMain.py
  GUI.py
Labels: bug
