Repository dejan-xd/Chess_DSL, pull requests merged in 2022-01, with the labels that each got.

#44 Highlight square logic Close #31
  ChessMain.py
  settings.json
Labels: user story

#45 Fix animations. Close #40
  ChessMain.py
Labels: bug

#48 Connect textX with Chess game. Close #30
  ChessMain.py
  InputThread.py
  requirements.txt
  settings.json
Labels: user story

#49 fixing issue Close #31
  ChessMain.py
Labels: bug, user story

#55 Chess AI. Close #12
  ChessAI.py
  ChessMain.py
  GUI.py
  GameState.py
  InputThread.py
  JsonParser.py
  Launch.py
  score_material.json
  settings.json
Labels: user story

#56 Add move information into console panel Close #46
  ChessMain.py
  InputThread.py
  JsonParser.py
  Utils.py
  settings.json
Labels: user story

#58 Fix console notations and game playing itself Close #57
  ChessMain.py
  GameState.py
  InputThread.py
  Utils.py
Labels: bug

#59 Bug/g UI
  GUI.py
  Launch.py
Labels: bug

#60 Add scroll to the panels. Close #50
  ChessMain.py
  InputThread.py
Labels: user story

#61 Threefold repetition and fifty move rules. Close#51
  ChessMain.py
  GUI.py
  GameState.py
Labels: user story

#62 Expand chess notations. Close #53
  ChessMain.py
  GameState.py
  InputThread.py
  settings.json
Labels: user story

#64 Draw text on screen Close #52
  ChessMain.py
  InputThread.py
  settings.json
Labels: user story

#65 Castling used output issue. Close #63
  ChessMain.py
  GameState.py
  InputThread.py
  JsonParser.py
  Utils.py
Labels: user story

#67 Chess AI bug. Close #66
  GUI.py
  settings.json
Labels: bug

#68 Create game handler commands. Close #29
  ChessMain.py
  InputThread.py
Labels: user story
